language: node_js
node_js:
  - node

notifications:
  slack:
    secure: JUaSs28h+yz+rgPZrt1QYh/XXWQ/SbQaWXQsQ2ktwe/S9LV8shYN3V+Hd0e3h9BBgEAHS2MQk0M9Pfd03iwEmP8qx4SAWyiY+N9Ncs7e3oo9cjam5sTCZRPBXfFmuykX4w+uP3j9c6cI4hkhCmbADf3wJMH+ZVJDZZ80zA/w2QnjzYzyCoeqHvBpSr5lCkZCx6pCdC0Nlk4O5LYOqa0arTefu5W/kUvBfQ7MTJw9bZZjrh/yl3klaSG14unp1dbww0VWPbss4N4nf0tapuFAIPOu4BLCSHGZWtjkrAGj8tv5f+FS3+YfalQgh3dHQn2sNXLi2GxY3Fj/lwB+h39+x+8dkHi1/FrKD7DV5pU0i0S0FvJE053CSe/LeI5VPReaKP/sabKnF1TGhe6LBTplPuga41DYG1b519nQOiYuD1K1OAXcdAvIimdKzGjk7toRz4iD8cbHc3YJ1Y9ifWIs6Gnh5tuYYWqV9Jasm/7L/aR4Raadtqh45SymmqjniLLpgfiWXoFovWpUCMlWZRsigY8rkMGqBR3QmeWlZS0G2dWVwiHXhlxVSDkVtUBPoBalizeWI1LJDBq8ZZLFmQwfm1Vq76TFZ/KCbs9Q/s8Cjd3DDHQzY65DwH39hKZT7YH0Auv8D3pbFm4+HBdcyuYU0WbVdN6PKhV7C74fRDG/egU=
    exclude:
      if: (fork = true)

install:
  - npm install
  - npm install -g codecov

script:
  - npm run test

after_success:
  - codecov
